apiVersion: v1
kind: Namespace
metadata:
  name: $tenant$
---
apiVersion: v1
kind: Service
metadata:
  name: ci-workshop-web
  namespace: $tenant$
  labels:
    app: ci-workshop
spec:
  ports:
    - port: 5005
  selector:
    app: ci-workshop
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ci-workshop-web
  namespace: $tenant$
  labels:
    app: ci-workshop
spec:
  selector:
    matchLabels:
      app: ci-workshop
      tier: frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ci-workshop
        tier: frontend
    spec:
      containers:
      - image: robertocordovac/ci-workshop-app:user10.1
        imagePullPolicy: IfNotPresent
        name: ci-workshop-web
        ports:
        - containerPort: 5005
          name: ci-workshop-web
        livenessProbe:
          httpGet:
            path: /
            port: ci-workshop-web
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: ci-workshop-web
          initialDelaySeconds: 5
